name: Mouhamed Aly Sidibe
description: "Blog de Mohamed Aly Sidibe"
baseurl: /jekyll-bulma
url: http://Sidibedev.github.io
download: 
social:
  github: Sidibedev
  email: Mouhamed.aly.sidibe96@gmail.com
  facebook: suudipp.carter
  twitter: mouhamedaly01
  instagram: momo__sidibe
  tumblr:
author:
  name: Mouhamed Aly Sidibe 
  bio: "Web & Mobile Developer , Junior Dev , Code Love "
  email: Mouhamed.aly.sidibe96@gmail.com
  image: /assets/images/author.jpg
  github: Sidibedev
  facebook: suudipp.carter
  twitter: mouhamedaly01
  instagram: momo__sidibe
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME