name: Jekyll Bulma
description: "Jekyll Bulma Theme, Bulma.io CSS Framework Jekyll Template for Developers"
baseurl: /jekyll-bulma
url: http://erayaydin.github.io
download: "https://github.com/erayaydin/jekyll-bulma/archive/master.zip"
social:
  github: Sidibedev
  email: Mouhamed.aly.sidibe96&gmaill.com
  facebook: suudipp.carter
  twitter: mouhamedaly01
  instagram: momo__sidibe
  tumblr:
author:
  name: Mouhamed Aly Sidibe 
  bio: "Web & Mobile Developer , Junior Dev , Code Love "
  email: Mouhamed.aly.sidibe96&gmaill.com
  image: /assets/images/author.jpg
  github: Sidibedev
  facebook: suudipp.carter
  twitter: mouhamedaly01
  instagram: momo__sidibe
  tumblr:
  show_on_post: true
permalink: /:categories/:title/
sass:
  style: compressed
paginate: 5
paginate_path: "/:num/"
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME